# Generated by Django 3.1.7 on 2021-04-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Congregate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BBC_Model',
            new_name='Content_Model',
        ),
        migrations.DeleteModel(
            name='Byteiota_Model',
        ),
        migrations.DeleteModel(
            name='Engadget_Model',
        ),
        migrations.DeleteModel(
            name='Medium_Model',
        ),
    ]
